### PR TITLE
Upgrade vulnerable dependencies and add contributing.md

### PR DESCRIPTION
**Pull request by kishaningithub**

### CODE REVIEW

**Comment by kishaningithub** [comment]
@assafkamil Any idea on why the github actions are not running for this PR?

**Comment by kishaningithub** [comment]
@assafkamil Have just fixed the CI trigger issue in this PR with the above commit

**Comment by kishaningithub** [comment]
@Geekoosh @assafkamil Would like your help on this upgrade PR

**Comment by assafkamil** [comment]
Closing as the issues were addresses in a different PR which already merged to master

**Pull request closed without merging**
